# Generated by Django 6.0.4 on 2026-05-27 19:46

import django.core.validators
import django.db.models.deletion
import users.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_index=True, max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\+\\d{9,15}$')])),
                ('gmail', models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True)),
                ('user_type', models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User'), ('SELLER', 'Seller')], db_index=True, default='USER', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
        ),
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=6)),
                ('is_used', models.BooleanField(db_index=True, default=False)),
                ('expires_at', models.DateTimeField(db_index=True, default=users.models.otp_expiry)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m')),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], db_index=True, max_length=10, null=True)),
                ('bio', models.TextField(blank=True, default='')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='users_user_phone_n_7fe504_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['gmail'], name='users_user_gmail_8aa8da_idx'),
        ),
        migrations.AddIndex(
            model_name='userotp',
            index=models.Index(fields=['user', 'code'], name='users_usero_user_id_3fbb01_idx'),
        ),
        migrations.AddIndex(
            model_name='userotp',
            index=models.Index(fields=['expires_at'], name='users_usero_expires_c1c2c7_idx'),
        ),
        migrations.AddIndex(
            model_name='userotp',
            index=models.Index(fields=['is_used'], name='users_usero_is_used_f161a1_idx'),
        ),
        migrations.AddConstraint(
            model_name='userotp',
            constraint=models.UniqueConstraint(fields=('user', 'code'), name='unique_user_otp_code'),
        ),
    ]
