# Generated by Django 6.0.4 on 2026-04-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_alter_user_is_superuser_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="userotp",
            name="users_usero_user_id_3fbb01_idx",
        ),
        migrations.AlterField(
            model_name="userotp",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
