# Generated by Django 6.0.3 on 2026-04-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_userotp_users_usero_user_id_3fbb01_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/%Y/%m"),
        ),
    ]
