# Generated by Django 6.0.3 on 2026-05-01 10:38

import django.core.validators
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0004_alter_userprofile_avatar"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userotp",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, db_index=True, max_length=254, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                db_index=True,
                max_length=15,
                unique=True,
                validators=[django.core.validators.RegexValidator("^\\+\\d{9,15}$")],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("ADMIN", "Admin"), ("USER", "User"), ("SELLER", "Seller")],
                db_index=True,
                default="USER",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="userotp",
            name="code",
            field=models.CharField(db_index=True, max_length=6),
        ),
        migrations.AlterField(
            model_name="userotp",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="userotp",
            name="expires_at",
            field=models.DateTimeField(db_index=True, default=users.models.otp_expiry),
        ),
        migrations.AlterField(
            model_name="userotp",
            name="is_used",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("MALE", "Male"), ("FEMALE", "Female")],
                db_index=True,
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["phone_number"], name="users_user_phone_n_7fe504_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_user_email_6f2530_idx"),
        ),
        migrations.AddIndex(
            model_name="userotp",
            index=models.Index(
                fields=["user", "code"], name="users_usero_user_id_3fbb01_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userotp",
            index=models.Index(
                fields=["expires_at"], name="users_usero_expires_c1c2c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userotp",
            index=models.Index(
                fields=["is_used"], name="users_usero_is_used_f161a1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="userotp",
            constraint=models.UniqueConstraint(
                fields=("user", "code"), name="unique_user_otp_code"
            ),
        ),
    ]
