# Generated by Django 6.0.4 on 2026-05-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0005_alter_userotp_options_alter_user_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="user",
            name="users_user_email_6f2530_idx",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="email",
            new_name="gmail",
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["gmail"], name="users_user_gmail_8aa8da_idx"),
        ),
    ]
