# Generated by Django 6.0.3 on 2026-05-01 12:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0002_category_is_deleted_and_more"),
        ("product", "0003_alter_favourite_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category"], name="product_pro_categor_2b9d78_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["seller"], name="product_pro_seller__45a808_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active"], name="product_pro_is_acti_9d034c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_available"], name="product_pro_is_avai_965bdd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(
                fields=["product"], name="product_pro_product_20de7e_idx"
            ),
        ),
    ]
