# Generated by Django 6.0.4 on 2026-05-27 19:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/%Y/%m/')),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='category.category')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CategoryProperty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('dropdown', 'Dropdown'), ('checkbox', 'Checkbox')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='category.category')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PropertyOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=100)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='category.categoryproperty')),
            ],
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='category_ca_slug_6890c5_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='category_ca_name_654722_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='category_ca_parent__ed1cbc_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active', 'is_deleted'], name='category_ca_is_acti_798749_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_deleted', 'is_active'], name='category_ca_is_dele_80a169_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryproperty',
            index=models.Index(fields=['category'], name='category_ca_categor_e5fded_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryproperty',
            index=models.Index(fields=['field_type'], name='category_ca_field_t_123b32_idx'),
        ),
        migrations.AddConstraint(
            model_name='categoryproperty',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_category_property'),
        ),
        migrations.AddConstraint(
            model_name='propertyoption',
            constraint=models.UniqueConstraint(fields=('property', 'value'), name='unique_property_option'),
        ),
    ]
