# Generated by Django 6.0.3 on 2026-05-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["slug"], name="category_ca_slug_6890c5_idx"),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["name"], name="category_ca_name_654722_idx"),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["parent"], name="category_ca_parent__ed1cbc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["is_active", "is_deleted"],
                name="category_ca_is_acti_798749_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["is_deleted", "is_active"],
                name="category_ca_is_dele_80a169_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="categoryproperty",
            index=models.Index(
                fields=["category"], name="category_ca_categor_e5fded_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="categoryproperty",
            index=models.Index(
                fields=["field_type"], name="category_ca_field_t_123b32_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="categoryproperty",
            constraint=models.UniqueConstraint(
                fields=("category", "name"), name="unique_category_property"
            ),
        ),
        migrations.AddConstraint(
            model_name="propertyoption",
            constraint=models.UniqueConstraint(
                fields=("property", "value"), name="unique_property_option"
            ),
        ),
    ]
