# Generated by Django 6.0.4 on 2026-05-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='category_ca_name_654722_idx',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='category_ca_is_dele_80a169_idx',
        ),
        migrations.RemoveIndex(
            model_name='categoryproperty',
            name='category_ca_categor_e5fded_idx',
        ),
        migrations.RemoveIndex(
            model_name='categoryproperty',
            name='category_ca_field_t_123b32_idx',
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='categoryproperty',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'order'], name='category_ca_parent__27e446_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='unique_category_per_parent'),
        ),
    ]
